# Generated by Django 2.1 on 2019-03-29 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_raiders_user_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raiders',
            name='user_link',
        ),
    ]
