# Generated by Django 2.1 on 2019-03-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190329_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip_id', models.CharField(default='None', max_length=200)),
                ('name', models.CharField(default='None', max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
