# Generated by Django 2.1 on 2019-03-30 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_effect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='effect',
            options={'verbose_name_plural': 'Effects'},
        ),
    ]
